spring.application.name=koi-coffee-backend
server.port=8080

# 1. Trỏ vào đúng Host mới và database koi_coffee_db
spring.datasource.url=jdbc:postgresql://koi-db16726-hounghoung04a-dcf1.j.aivencloud.com:13589/defaultdb?sslmode=require
spring.datasource.username=avnadmin

# 2. BẢO MẬT: Dùng biến môi trường để GitHub không chặn Push
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. QUAN TRỌNG: Phải để "none". Không cho phép Spring Boot tự động sửa bảng, làm hỏng dữ liệu SQL bạn vừa nạp.
spring.jpa.hibernate.ddl-auto=update

# Hiển thị log SQL để dễ kiểm tra
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true